#!/bin/bash

# Check if the mmseqs executable path is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <path_to_mmseqs_executable>"
    exit 1
fi

MMSEQS_EXEC="$1"

# Create a directory to store the help output
mkdir -p mmseqs_help_output

# List of all MMseqs2 modules (obtained from CommandDeclarations.h)
MODULES=(
    "align"
    "alignall"
    "alignbykmer"
    "aliasdb"
    "apply"
    "besthitperset"
    "cluster"
    "clusterupdate"
    "clusthash"
    "clust"
    "combinepvalperset"
    "compress"
    "concatdbs"
    "convertalis"
    "convertmsa"
    "cpdb"
    "createdb"
    "createindex"
    "createlinindex"
    "createseqfiledb"
    "createsubdb"
    "createtaxdb"
    "createtsv"
    "db2tar"
    "decompress"
    "easy-cluster"
    "easy-linclust"
    "easy-linsearch"
    "easy-rbh"
    "easy-search"
    "easy-taxonomy"
    "expandaln"
    "extractorfs"
    "extractframes"
    "extractalignedregion"
    "filterdb"
    "filterresult"
    "filtertaxdb"
    "filtertaxseqdb"
    "gappedprefilter"
    "gpuserver"
    "kmermatcher"
    "kmersearch"
    "lca"
    "lcaalign"
    "linclust"
    "linsearch"
    "lndb"
    "makepaddedseqdb"
    "map"
    "masksequence"
    "mergedbs"
    "mergeclusters"
    "mergeresultsbyset"
    "msa2profile"
    "msa2result"
    "multihitdb"
    "multihitsearch"
    "mvdb"
    "offsetalignment"
    "orftocontig"
    "prefilter"
    "prefixid"
    "proteinaln2nucl"
    "rbh"
    "recoverlongestorf"
    "renamedbkeys"
    "rescorediagonal"
    "result2dnamsa"
    "result2flat"
    "result2msa"
    "result2profile"
    "result2rbh"
    "result2repseq"
    "result2stats"
    "reverseseq"
    "search"
    "setextendeddbtype"
    "sortresult"
    "splitdb"
    "splitsequence"
    "subtractdbs"
    "suffixid"
    "summarizealis"
    "summarizeresult"
    "swapdb"
    "swapresults"
    "tar2db"
    "taxonomy"
    "taxonomyreport"
    "touchdb"
    "translatenucs"
    "translateaa"
    "tsv2db"
    "tsv2exprofiledb"
    "ungappedprefilter"
    "unpackdb"
    "view"
)

# Iterate through the modules and get their help output
for module in "${MODULES[@]}"; do
    echo "Getting help for: mmseqs $module"
    # Execute the command and save output to a file
    "${MMSEQS_EXEC}" "$module" -h > "mmseqs_help_output/${module}.txt" 2>&1
    if [ $? -ne 0 ]; then
        echo "Error getting help for $module. Check mmseqs_help_output/${module}.txt for details."
    fi
done

echo "All help outputs saved to the 'mmseqs_help_output' directory."
